language: minimal
services:
 - docker

script:
 - ./docker_build.sh

# Deploy to GitHub pages
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: artifacts
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  repo: lietu/BetterOption
  on:
    branch: master
